### PR TITLE
[dist] Use GitHub Actions

### PR DESCRIPTION
**Pull request by decompil3d**
TravisCI.org is going away sometime soon. I think they want folks to use their ".com" product instead. This PR just swaps to using GitHub Actions as it's free for open-source and works pretty well.

### CODE REVIEW

**Comment by decompil3d** [comment]
Since this is from a fork, it won't run the Action. It might need some massaging to get just right, so feel free to either merge it and iterate yourself, or close and commit the new file under your own PR.

**Comment by decompil3d** [comment]
Actually, looks like it just runs on my fork instead. So I now have it all working. Should be mergeable and you could then disable Travis if you want.

**Comment by decompil3d** [comment]
@tchellomello This is ready for your review

**Comment by tchellomello** [comment]
Thanks for your contribution @decompil3d

**Comment by decompil3d** [comment]
Glad it helps. Btw, you can delete your travis.yml if you're good with GH Actions.

**Pull request merged**
