### PR TITLE
Added ability to change chime ringtones for motion and dings

### PR DESCRIPTION
**Pull request by tchellomello**
**Description**:

This PR allows the user to modify the chime wave sound for motion and ding for an external Ring chime. 
For example:

```python
from ring_doorbell import Ring
myring = Ring('foo@bar', 'secret')

chime = myring.chimes[0]
chime.name
'Downstairs'

chime.ringtone_ding
'Ding-Dong'

chime.ringtone_motion
'Upbeat'

# changing ringtone
chime.ringtones_ding_available
['Charge!',
 'Ding-Dong',
 'Dogs Barking',
 'Doorbot',
 'Flashback',
 'Harp',
 'Navi',
 'Ring Alert 2',
 'Ring Alert 3',
 'Ring Default',
 'Train Whistle',
 'Triangle',
 'Upbeat',
 'Xylophone']

# this operation takes about 10 seconds to get your chime updated
chime.ringtone_ding = 'Train Whistle'

# wait about 10 seconds and then refresh it
chime.update()

chime.ringtone_ding
'Train Whistle'
```

**Fixes issue**: https://github.com/tchellomello/python-ring-doorbell/issues/19

### CODE REVIEW

**Comment by tchellomello** [comment]
@syphernl could you test this PR to see if works for you?

Thank you

**Comment by syphernl** [comment]
Awesome, will test this tonight when I'm at home! :smile:

**Comment by syphernl** [comment]
Seems to be working just fine! Choo-Choo! 👍

**Comment by tchellomello** [comment]
Awesome @syphernl. 

I'm going ahead and merge this then!

Thanks for your help! :1st_place_medal:

**Pull request merged**
