### PR TITLE
Add support for Floodlight Cam Pro

### PR DESCRIPTION
**Pull request by twasilczyk**

### CODE REVIEW

**Comment by nhorvath** [comment]
Bump. Please merge this so home assistant recognizes this as a light.

**Review by tchellomello — APPROVED** [review]

**Comment by tchellomello** [comment]
> Bump. Please merge this so home assistant recognizes this as a light.

Planing to release it over the weekend.

**Comment by george-gwu** [comment]
Any updates on releasing this update?

**Comment by kooscode** [comment]
any updates?

**Comment by sdb9696** [comment]
This update is now released as 0.7.3

**Pull request merged**
