### PR TITLE
Add support for downloading snapshot from doorbell

### PR DESCRIPTION
**Pull request by MorganBulkeley**
Adds support for downloading snapshots from the doorbell

https://support.ring.com/hc/en-us/articles/360000685566-Camera-Previews-FAQ

### CODE REVIEW

**Comment by 10der** [comment]
look like it doesn't work.

```
if myring.is_connected:
   dev = myring.doorbells[0]
   print(dev.last_recording_id)
   snapshot = dev.get_snapshot()
   print(snapshot)
```
console
```
python.exe ring.py
2332445056122158153
False
``

**Comment by 10der** [comment]
UPD: about timestamps and request_time
```
            print(response["timestamps"][0]["timestamp"] / 1000)
            print(request_time)
```
```
1544388452
1544388505.49
```
False

**Comment by MorganBulkeley** [comment]
Thanks for taking a look at this, I've been really busy these past few weeks and haven't had time to troubleshoot.

**Comment by odenisenko** [comment]
JFYI: sometimes this function (not @MorganBulkeley) I am saying about ring api. working is not properly,
for example, my middle dau now went to walk. ring app said about motion but api said
```
if myring.is_connected:
   dev = myring.doorbells[0]
   ts = int(dev.get_last_snapshot_time())
   print(datetime.utcfromtimestamp(ts).strftime('%Y-%m-%d %H:%M:%S'))
```
python. ring.py
2018-12-15 08:55:21

be sensible of the fact that now 11:00 (AM)

**Comment by problemss** [comment]
@MorganBulkeley is this working yet? I ran into the same error @odenisenko did. So I will also try to remove the `check response["timestamps"][0]["timestamp"] / 1000 > request_time` section as well.

**Comment by odenisenko** [comment]
> @MorganBulkeley is this working yet? I ran into the same error @odenisenko did. So I will also try to remove the `check response["timestamps"][0]["timestamp"] / 1000 > request_time` section as well.

last month my code is:
```
    def get_snapshot(self, retries=3, delay=1):
        """Take a snapshot and download it"""
        url = API_URI + SNAPSHOT_TIMESTAMP_ENDPOINT
        payload = {"doorbot_ids": [self._attrs.get('id')]}
        self._ring.query(url, json=payload)
        request_time = time.time()
        for _ in range(retries):
            time.sleep(delay)
            response = self._ring.query(url, method="POST", json=payload,
                                                            raw=1).json()
            # print(request_time - response["timestamps"][0]["timestamp"] / 1000)
            if request_time - response["timestamps"][0]["timestamp"] / 1000 < 200:
                return self._ring.query(API_URI + SNAPSHOT_ENDPOINT.format(
                                  self._attrs.get('id')), raw=True).content
        return False
```
yes, it's ugly but it works like a charm.

**Comment by problemss** [comment]
@odenisenko Thank you! Looks like it is working. Just have to save the contents of the snapshot now!

**Comment by problemss** [comment]
@odenisenko @MorganBulkeley Thank you both. This is working perfectly!!!

**Comment by schwarzwals** [comment]
Hey guys, when I do :

if myring.is_connected:
   dev = myring.doorbells[0]
   print(dev.last_recording_id)
   snap = dev.get_snapshot()
   print(snapshot)

I'm getting the id of the last recording, but no luck with the snapshot :( any thoughts ? 

6645686099222589186

Traceback (most recent call last):
  File "/Users/home/Desktop/ring.py", line 25, in <module>
    snap = dev.get_snapshot()

**Comment by problemss** [comment]
This is not checked into the main branch.

**Comment by schwarzwals** [comment]
@problemss what do u mean ? sorry :(

**Comment by odenisenko** [comment]
snapshot endpoint now return 401

**Comment by problemss** [comment]
Good to know I am not the only one receiving this error.

**Comment by tybritten** [comment]
I'm running 0.2.3 with a ring pro and the snapshot functionality works fine in the app, but when I try to call it I'm getting this:
```
6672079068379901730
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/usr/local/lib/python3.7/site-packages/ring_doorbell/doorbot.py", line 378, in get_snapshot
    self._ring.query(url, json=payload)
  File "/usr/local/lib/python3.7/site-packages/ring_doorbell/__init__.py", line 207, in query
    self._authenticate()
  File "/usr/local/lib/python3.7/site-packages/ring_doorbell/__init__.py", line 155, in _authenticate
    req.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.ring.com/clients_api/session
```
All the other commands work fine, it's only get_snapshot that's getting an unauthorized message.

**Comment by haimiko** [comment]
Same 401 Auth error.  It's because the _get_oauth_token is failing when getting the snapshot response 400

b'{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed."}\n'

But postman returns just fine for the very same oath data/endpoint.  So i suspect something in the session.  I tried preventing session reuse without luck.

**Pull request merged**
