### PR TITLE
[feat] Add support for Light Groups

### PR DESCRIPTION
**Pull request by decompil3d**
My original goal here was to support the Ring Beams line of products (e.g. lighting transformers), but it seems like their API for that product line is vastly different than the other products, likely because it was from an acquisition. The new API is all web sockets based. And I'm no Python expert, so I'm not able to really dig in to add support for that.

But, it looks like their REST API _does_ provide support for toggling Light Groups. And when you add a new Transformer device to your account, they prompt you to add it into a group. So this is my simpler approach to add support for this product -- just exposing a method to retrieve Light Groups and toggle their light status.

I've confirmed with my own device that this code works as expected. And it is all additive, so it won't cause any API breaks or sudden additional devices for existing consumers of this library.

Like I said, I am definitely not a Python expert. I primarily write JS. So please feel free to tell me where I'm not doing things right or not in the Python way. Happy to adjust as needed.

## TODO

- [x] Still need to write tests

### CODE REVIEW

**Comment by decompil3d** [comment]
Looks like the linter failure is broken in `master` as well.

**Comment by decompil3d** [comment]
@tchellomello This is ready for your review

**Comment by decompil3d** [comment]
Hey @tchellomello -- just wanted to ping to see if you can take a look at this PR and merge if you're alright with it. Let me know if you have any concerns. Thanks!

**Comment by tchellomello** [comment]
Thanks again @decompil3d !! You rock!

**Comment by decompil3d** [comment]
Awesome! Thanks for merging. Mind publishing a release? I'm planning to make a PR against Home Assistant to apply this new light group support.

**Pull request merged**
