### PR TITLE
Basic intercom support

### PR DESCRIPTION
**Pull request by rautsch**
Added basic support for the Ring Intercom.
The main focus was on the ability to trigger door opening and send invitations.

### CODE REVIEW

**Comment by tispokes** [comment]
Would be nice to have this feature

**Comment by lastfreeusernameicouldfind** [comment]
why is this PR hanging since Dec 2022? Would be very nice to get this feature merged.

**Comment by sdb9696** [comment]
HI @rautsch, I have recently been added as a maintainer on this library.  There seems to be some demand on homeassistant for this [feature](https://community.home-assistant.io/t/feature-request-ring-intecom-intergration/490672).  Would you be willing to bring this PR up to date so I can review it and we can test it with your intercom devices?

**Comment by rautsch** [comment]
> HI @rautsch, I have recently been added as a maintainer on this library. There seems to be some demand on homeassistant for this [feature](https://community.home-assistant.io/t/feature-request-ring-intecom-intergration/490672). Would you be willing to bring this PR up to date so I can review it and we can test it with your intercom devices?

Hey,
Great to hear! I think I can look into it in the next few days.
What needs to be done in order to merge? (I guess tests, docu, extend feature support)

**Comment by sdb9696** [comment]
Hi @rautsch.  Yes, basically it looks pretty good but you'll need to rebase to the latest code.  N.B. the library has a cli now which might help you with integration testing.  So:

1. Rebase - I'd recommend squashing all your commits down to one commit first so the rebase is easier.
2. Docs - (don't worry about too much detail here, we can always improve later)
3. Add tests and mock fixtures for the new api calls.  This [PR](https://github.com/tchellomello/python-ring-doorbell/pull/282) shows what's needed and should help with it.
4. Rename device_id in the constructor to device_api_id to avoid confusion with the device_id value returned from the api (which is usually the mac)

Thanks!

**Comment by andrew-rinato** [comment]
I am actually just working on this myself. I hope to have something up today for review. Added a couple more settings setters as well.

**Comment by sdb9696** [comment]
Hi @andrew-rinato.  Are the additional settings setters needed for the intercom devices or are they independent?  If they're independent it would be better to have a separate PR to ease the review.

**Comment by andrew-rinato** [comment]
Hi @sdb9696 I just created a separate PR. You'll see the device settings I've added, which are specific to the intercom "other" device category. Most correspond to settings in the app, but there is an additional one I exposed that I believe will be of interest to many others (gauging from https://github.com/dgreif/ring/issues/1083).

**Comment by sdb9696** [comment]
Closing as addressed by https://github.com/tchellomello/python-ring-doorbell/pull/330

**Pull request closed without merging**
